### PR TITLE
Update WifiLedShopLight.py

### PR DESCRIPTION
**Pull request by blind-coder**
turn_on: Only toggle if not on already

turn_off: Only toggle if not off already

### CODE REVIEW

**Comment by samhstein** [comment]
hi,

not sure this is necessary, cant hurt, but it should know / keep the correct state and only have the option to turn on or turn off setup properly on the ui? that is that the ui should always have state right and call on / off....

**Comment by blind-coder** [comment]
The ui does have the state, but if you create an automation to "turn on" the light it shouldn't be necessary to check the state first, which isn't even possible if you chain multiple actions like "turn off phone deflection" and "turn on lights". You could do multiple automations, one for each action, but that would create additional maintenance overhead.
Finally, it just feels unintuitive that an action to" turn on" the light would turn it off if it's on already. I spent a sizable account of an afternoon trying to figure out if my controller is broken :)

**Comment by samhstein** [comment]
never thought about automations..... ours our cove lights that just get used occasionally

**Comment by blind-coder** [comment]
I have my entire staircase illuminated with one of these, 15 steps with 26 LEDs each on a single sp108e. Works like a charm, but needed a lot of cabling and 4 distinct power lines. I turn these on automatically when someone comes home, or at night when one of two motion sensors gets triggered.

Thank you for merging :)

**Pull request merged**
